### ISSUE TITLE
Search algorithm error

### ISSUE THREAD

**Issue by poupryc** [FiftyNine/ScpperDB#33]
Hello !

We noticed a problem with the algorithm: with the [following call](http://scpper.com/api/find-pages?site=fr&title=104&limit=2), for 104, the API will first return 104-FR and after 104. This is problematic in the sense that if we were looking for 104-FR, we would have run a search for 104-FR.

Perhaps getting the most similar results first would be a good solution?

Thank you in advance

**Comment by FiftyNine** [comment]
I've modified searching algorithm somewhat so results should take in account how different is page's title from the query.
The problem is it's never going to be perfect. 
For example, right now searching for "173" on the english wiki will return the page titled "173" as the first result even though most people expect to see "scp-173".
I'm not going to fiddle with search anymore, unless its current version breaks in some severe way,
