### ISSUE TITLE
[BUG] Scpper Rating Isn't Accurate with Wiki Rating

### ISSUE THREAD

**Issue by 2BoredPlayer** [FiftyNine/ScpperDB#44]
The Scpper Rating isn't accurate with the Wiki Rating. On [the Wiki](https://scp-wiki.wikidot.com/scp-8000#:~:text=%C2%BB%20SCP%2D8000-,Rating,-%3A%C2%A0), SCP-8000 has around a +580 rating. But on [Scpper](https://scpper.com/page/1452608893#:~:text=20%0AContributors%3A%20PlaguePJP-,Rating), SCP-8000 has around a +260 rating (despite showing [several more votes in its voting section](https://scpper.com/page/1452608893#:~:text=%23-,User,-Vote)).

**Scpper should accurately reflect on the Wiki rating**,
or at least **use [its voting section](https://scpper.com/page/1452608893#:~:text=%23-,User,-Vote) for the Scpper rating**.

Screenshots
---
![Screenshot 2024-03-18 3 27 20 AM](https://github.com/FiftyNine/ScpperDB/assets/119268684/7f36e7e8-5612-44a1-a68e-139ce245c4b9) ![Screenshot 2024-03-18 3 27 55 AM](https://github.com/FiftyNine/ScpperDB/assets/119268684/fee54df0-cd8c-4386-a68f-90bd7c6c7521)

**Comment by 2BoredPlayer** [comment]
*Screenshots are from this morning, so these ratings may look a little outdated now

**Comment by FiftyNine** [comment]
Note: Wikidot membership module is often broken so scpper can't see who's a member of a branch and who isn't. Votes from non-members aren't counted, hence the issue.
Possible solutions: 
 - Disregard membership and count all votes
 - Devise an alternative method for establishing membership based on activity.

**Comment by 2BoredPlayer** [comment]
@FiftyNine 
**I recommend the 1st option of counting all votes, even non-members**, to be more accurate with the Wiki rating. This could also solve the issue of some articles [being rated too negatively](https://scpper.com/page/1452652330) then [they actually are](https://scp-wiki.wikidot.com/scp-8199).

**Comment by FiftyNine** [comment]
Scpper only counts votes from members specifically to exclude accounts who had engaged in vote manipulation, and subsequently were caught and banned from the wiki.
Of course now, when member list on the english wiki is broken it does more harm than good.
The only other way to check if an account is a member that I know of requires fetching a user profile page for each account, which would consume too much bandwidth and processing power, so I will have to fall back to counting all votes.

**Comment by FiftyNine** [comment]
Fixed in the latest commit on ScpCrawler.

I opted for an alternative way to establish if a user is a member by checking their recent activity, i.e. if someone voted on a wiki or created a revision, they are a member. Date of joining for such users is taken from their first recorded activity on the wiki. 

This is preferable to changing how rating calculation work because this approach solves some related issues (missing membership on user profile, list of members for the wiki, etc). There is now way to detect if account is not longer a member of the wiki, but this is something that we will have to accept.
